### PR TITLE
Merge patch-staging into master

### PR DESCRIPTION
**Pull request by aaronhurt**
Draft PR to accumulate patches.

### CODE REVIEW

**Comment by tschettervictor** [comment]
I think I'm pretty well satisfied with the changes in this patch. Since this is my first official project on Github, I'm not 100% sure what I'm doing with all the reviews and such, so you'll have to bear with me.

**Review by tschettervictor — APPROVED** [review]

**Comment by aaronhurt** [comment]
Ohh no, we shouldn't have merged that. I don't think this code is ready.

**Comment by aaronhurt** [comment]
There are some code errors here and quite a bit of formatting that needs to be sorted out. I'm going to setup the `shfmt` and `spellcheck` actions on this repo to catch these going forward.

**Comment by tschettervictor** [comment]
Sorry bout that. I'm still learning. What do you need me to change?

**Comment by aaronhurt** [comment]
I'm working on a few things now, I'll post an update shortly.

**Pull request merged**
